### ISSUE TITLE
Random crash while right-clicking on a link

### ISSUE THREAD

**Issue by yan12125** [lxqt/qtermwidget#241]
##### Expected Behavior
QTerminal never crashes

##### Current Behavior
Sometimes it crashes when right-clicking on a link

<details>
<summary>
gdb backtrace
</summary>

```
#0  0x0000555b435f7d30 in ?? ()
#1  0x00007fdbf53cdccc in Konsole::TerminalDisplay::filterActions (this=0x555b43529740, position=..., 
    parent=parent@entry=0x7ffc68e38fa0) at /usr/src/debug/qtermwidget/lib/TerminalDisplay.cpp:1972
#2  0x00007fdbf53ba8e5 in QTermWidget::filterActions (this=this@entry=0x555b46787fd0, position=..., parent=parent@entry=0x7ffc68e38fa0)
    at /usr/src/debug/qtermwidget/lib/qtermwidget.cpp:676
#3  0x0000555b4155435b in TermWidgetImpl::customContextMenuCall (this=0x555b46787fd0, pos=...)
    at /usr/src/debug/qterminal/src/termwidget.cpp:141
#4  0x00007fdbf42f93e0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#5  0x00007fdbf4cbd366 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/libQt5Widgets.so.5
#6  0x00007fdbf4cd8848 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#7  0x00007fdbf4c96e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007fdbf4c9eb20 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007fdbf42ce8f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#10 0x00007fdbf4cf3569 in ?? () from /usr/lib/libQt5Widgets.so.5
#11 0x00007fdbf4cf5c67 in ?? () from /usr/lib/libQt5Widgets.so.5
#12 0x00007fdbf4c96e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007fdbf4c9e671 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007fdbf42ce8f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#15 0x00007fdbf46a29be in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#16 0x00007fdbf46a3e26 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#17 0x00007fdbf467d75c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Gui.so.5
#18 0x00007fdbefeac99c in ?? () from /usr/lib/libQt5XcbQpa.so.5
#19 0x00007fdbf303ea2f in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#20 0x00007fdbf30405e9 in ?? () from /usr/lib/libglib-2.0.so.0
#21 0x00007fdbf304062e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#22 0x00007fdbf43245a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#23 0x00007fdbf42cd58c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#24 0x00007fdbf42d5896 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#25 0x0000555b4154161f in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/qterminal/src/main.cpp:203
```
</details>

##### Possible Solution
Need investigation

##### Steps to Reproduce (for bugs)
1. Right-click on a link multiple times

##### Context
A crashed terminal sucks

##### System Information
* Distribution & Version: 
* Kernel: 4.19.12.arch1-1
* Qt Version: 5.12.0
* Package version: 0.9.0.84.gf475050-1

**Comment by yan12125** [comment]
"Fixed", after reverting two bad pull requests.
